const PathConstants = {
  STARTPAGE: "/",
  SELECTEDPAGE: "/selected-page",
  COOKBOOKBLOGPAGE: "/cookbookblog-page",
  ABOUTPAGE: "/about-page",
  RECIPEPAGE01: "/recipe-page01",
  RECIPEPAGE02: "/recipe-page02",
  RECIPEPAGE03: "/recipe-page03",
  RECIPEPAGE04: "/recipe-page04",
  RECIPEPAGE05: "/recipe-page05",
  RECIPEPAGE06: "/recipe-page06",
  RECIPEPAGE07: "/recipe-page07",
  RECIPEPAGE08: "/recipe-page08",
  RECIPEPAGE09: "/recipe-page09",
  RECIPEPAGE10: "/recipe-page10",
  RECIPEPAGE11: "/recipe-page11",
  RECIPEPAGE12: "/recipe-page12",
  RECIPEPAGE13: "/recipe-page13",
  RECIPEPAGE14: "/recipe-page14",
  RECIPEPAGE15: "/recipe-page15",
  RECIPEPAGE16: "/recipe-page16",
  RECIPEPAGE17: "/recipe-page17",
  RECIPEPAGE18: "/recipe-page18",
  RECIPEPAGE19: "/recipe-page19",
  RECIPEPAGE20: "/recipe-page20",
  RECIPEPAGE21: "/recipe-page21",
  RECIPEPAGE22: "/recipe-page22",
  RECIPEPAGE23: "/recipe-page23",
  RECIPEPAGE24: "/recipe-page24",
  RECIPEPAGE25: "/recipe-page25",
  RECIPEPAGE26: "/recipe-page26",
  RECIPEPAGE27: "/recipe-page27",
  RECIPEPAGE28: "/recipe-page28",
  POSTPAGE: "/post-page",
}
export default PathConstants;