interface AdvicesType {
  id: string | number | bigint;
  bgImage: string;
  description: string;
  title: string;
  adviceText: string;
}
  
export const advices: AdvicesType[] = [{
  id: "adV01",
  bgImage: "/advice01-recipe-01.jpg",
  description: "Croutons with omelette",
  title: "Helpful advice!",
  adviceText: "Why are my omelette not fluffy? Here are some reasons your omelette might not be fluffy. Eggs aren't fully beaten. You need to whip the eggs until the mixture is completely homogenous (uniform throughout). A dirty bowl. If you whip your eggs in an oily, dirty bowl, it will cause them to not be fluffy when cooked. A pan that's too large. If you use a pan that is larger than 8″ your omelette will be too thin and not fluffy.",
}, {
  id: "adV02",
  bgImage: "/advice02-recipe-01.jpg",
  description: "Croutons with omelette",
  title: "Helpful advice!",
  adviceText: "If you want to make sure the outside of your omelet looks extra smooth and glossy, paint it with some butter while it's still hot. This will help you get the professional-looking omelet you crave.",
}, {
  id: "adv03",
  bgImage: "/advice03-recipe-01.jpg",
  description: "Croutons with omelette",
  title: "Helpful advice!",
  adviceText: "Unless you're making a soufflé omelet, you're not whipping eggs to stiff peaks for your breakfast meal. It can be tempting to take things to the opposite extreme and just barely beat the eggs before adding them to the pan. While it might not seem like a big deal, your omelets will come out better if you thoroughly whip the eggs.",
},{
  id: "adv04",
  bgImage: "/advice01-recipe-02.jpg",
  description: "Chicken broth with vegetables",
  title: "Helpful advice!",
  adviceText: "Can I add garlic and onion? Yes. If you add freshly minced onion and minced garlic, do not omit the garlic and onion powder from the homemade condensed soup.",
}, {
  id: "adv05",
  bgImage: "/advice02-recipe-02.jpg",
  description: "Chicken broth with vegetables",
  title: "Helpful advice!",
  adviceText: "How long do I need to simmer the chicken broth for? At least 7 hours. You need to allow the broth to draw out the nutrients from the chicken bones to create a flavourful and nutritious broth.",
}, {
  id: "adv06",
  bgImage: "/advice03-recipe-02.jpg",
  description: "Chicken broth with vegetables",
  title: "Helpful advice!",
  adviceText: "How to store the chicken broth: Once the broth has cooled completely you can pour it into tempered glass jars, or zip lock bags and freeze for up to 3 months.",
}, {
  id: "adv07",
  bgImage: "/advice01-recipe-03.jpg",
  description: "Poached eggs on rye buns",
  title: "Helpful advice!",
  adviceText: "For a firm white and runny yolk you'll want to poach the eggs for 3-4 minutes. I prefer a 3 minute poached egg. And if you plan to poach a batch of eggs ahead of time and reheat later, just keep in mind that reheating may firm up the eggs a little more as well.",
}, {
  id: "adv08",
  bgImage: "/advice02-recipe-03.jpg",
  description: "Poached eggs on rye buns",
  title: "Helpful advice!",
  adviceText: "The joy of a poached egg is its perfectly runny yolk and just-set whites. The yolk spills forth in a rich cascade, saucing your noodles, enriching your ramen broth, or adding depth to plain toast. Overcooking ruins this — no one likes to cut into a poached egg to find a pale yellow, immovable center.",
}, {
  id: "adv09",
  bgImage: "/advice03-recipe-03.jpg",
  description: "Poached eggs on rye buns",
  title: "Helpful advice!",
  adviceText: "Bringing a sopping wet poached egg to the table is definitely not a good idea. Not only does the excess water dilute the flavor of the egg, but it also ruins any toast or other crispy elements in your breakfast and makes sauces slide right off.",
}, {
  id: "adv10",
  bgImage: "/advice01-recipe-04.jpg",
  description: "Baked salmon with herbs",
  title: "Helpful advice!",
  adviceText: "If you're cooking your salmon in high heat (425°F), you'll want to aim for four to six minutes per half-inch of thickness. Since most fillets measure about one inch in the thickest part, start checking after around eight minutes in the oven.",
}, {
  id: "adv11",
  bgImage: "/advice02-recipe-04.jpg",
  description: "Baked salmon with herbs",
  title: "Helpful advice!",
  adviceText: "Baked salmon will stay good in the refrigerator for up to two days. Refrigerate any leftovers right away. We recommend storing baked salmon in a glass container with a well-sealed lid since fish odors can linger in plastic containers even after washing.",
}, {
  id: "adv12",
  bgImage: "/advice03-recipe-04.jpg",
  description: "Baked salmon with herbs",
  title: "Helpful advice!",
  adviceText: "Salmon goes well with many herbs and spices: parsley, dill, basil, tarragon, sage, rosemary, bay leaves, thyme, fennel, oregano, chilli powder, and cumin... the list is endless. Season salmon before cooking. Seasoning will enhance the flavour of the fish, help the flesh stay firm, and preserve the vibrant pink colour of the salmon.",
}, {
  id: "adv13",
  bgImage: "",
  description: "Pancakes with honey and blackberries",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv14",
  bgImage: "",
  description: "Pancakes with honey and blackberries",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv15",
  bgImage: "",
  description: "Pancakes with honey and blackberries",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv16",
  bgImage: "",
  description: "Pasta with champignons",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv17",
  bgImage: "",
  description: "Pasta with champignons",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv18",
  bgImage: "",
  description: "Pasta with champignons",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv19",
  bgImage: "",
  description: "Grilled shrimp salad",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv20",
  bgImage: "",
  description: "Grilled shrimp salad",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv21",
  bgImage: "",
  description: "Grilled shrimp salad",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv22",
  bgImage: "",
  description: "Meatloaf with prunes",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv23",
  bgImage: "",
  description: "Meatloaf with prunes",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv24",
  bgImage: "",
  description: "Meatloaf with prunes",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv25",
  bgImage: "",
  description: "Strawberries and arugula salad",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv26",
  bgImage: "",
  description: "Strawberries and arugula salad",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv27",
  bgImage: "",
  description: "Strawberries and arugula salad",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv28",
  bgImage: "",
  description: "Chocolate custard cream",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv29",
  bgImage: "",
  description: "Chocolate custard cream",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv30",
  bgImage: "",
  description: "Chocolate custard cream",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv31",
  bgImage: "",
  description: "Guacamole and Tuna Toast",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv32",
  bgImage: "",
  description: "Guacamole and Tuna Toast",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv33",
  bgImage: "",
  description: "Guacamole and Tuna Toast",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv34",
  bgImage: "",
  description: "Egg on toast",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv35",
  bgImage: "",
  description: "Egg on toast",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv36",
  bgImage: "",
  description: "Egg on toast",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv37",
  bgImage: "",
  description: "Cheese casserole",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv38",
  bgImage: "",
  description: "Cheese casserole",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv39",
  bgImage: "",
  description: "Cheese casserole",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv40",
  bgImage: "",
  description: "Chicken legs in honey sauce",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv41",
  bgImage: "",
  description: "Chicken legs in honey sauce",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv42",
  bgImage: "",
  description: "Chicken legs in honey sauce",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv43",
  bgImage: "",
  description: "Granola and raspberries in yogurt",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv44",
  bgImage: "",
  description: "Granola and raspberries in yogurt",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv45",
  bgImage: "",
  description: "Granola and raspberries in yogurt",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv46",
  bgImage: "",
  description: "Grilled beef steaks",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv47",
  bgImage: "",
  description: "Grilled beef steaks",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv48",
  bgImage: "",
  description: "Grilled beef steaks",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv49",
  bgImage: "",
  description: "Pancakes with cottage cheese",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv50",
  bgImage: "",
  description: "Pancakes with cottage cheese",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv51",
  bgImage: "",
  description: "Pancakes with cottage cheese",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv52",
  bgImage: "",
  description: "Feta and olives salad",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv53",
  bgImage: "",
  description: "Feta and olives salad",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv54",
  bgImage: "",
  description: "Feta and olives salad",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv55",
  bgImage: "",
  description: "Creamy fish soup",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv56",
  bgImage: "",
  description: "Creamy fish soup",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv57",
  bgImage: "",
  description: "Creamy fish soup",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv58",
  bgImage: "",
  description: "Cheese pie with bacon",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv59",
  bgImage: "",
  description: "Cheese pie with bacon",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv60",
  bgImage: "",
  description: "Cheese pie with bacon",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv61",
  bgImage: "",
  description: "Lemon cream jelly",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv62",
  bgImage: "",
  description: "Lemon cream jelly",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv63",
  bgImage: "",
  description: "Lemon cream jelly",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv64",
  bgImage: "",
  description: "Cod with vegetables",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv65",
  bgImage: "",
  description: "Cod with vegetables",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv66",
  bgImage: "",
  description: "Cod with vegetables",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv67",
  bgImage: "",
  description: "Mint lemonade",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv68",
  bgImage: "",
  description: "Mint lemonade",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv69",
  bgImage: "",
  description: "Mint lemonade",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv70",
  bgImage: "",
  description: "Curd cookies",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv71",
  bgImage: "",
  description: "Curd cookies",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv72",
  bgImage: "",
  description: "Curd cookies",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv73",
  bgImage: "",
  description: "Meatballs in tomato sauce",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv74",
  bgImage: "",
  description: "Meatballs in tomato sauce",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv75",
  bgImage: "",
  description: "Meatballs in tomato sauce",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv76",
  bgImage: "",
  description: "Baked apples with cinnamon",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv77",
  bgImage: "",
  description: "Baked apples with cinnamon",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv78",
  bgImage: "",
  description: "Baked apples with cinnamon",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv79",
  bgImage: "",
  description: "Eggplant with cheese",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv80",
  bgImage: "",
  description: "Eggplant with cheese",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv81",
  bgImage: "",
  description: "Eggplant with cheese",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv82",
  bgImage: "",
  description: "Oatmeal with nuts",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv83",
  bgImage: "",
  description: "Oatmeal with nuts",
  title: "Helpful advice!",
  adviceText: "000",
}, {
  id: "adv84",
  bgImage: "",
  description: "Oatmeal with nuts",
  title: "Helpful advice!",
  adviceText: "000",
}];