interface CardType {
  id: string | number | bigint;
  linkTo: string;
  imageSrc: string;
  title: string;
  mealTime: string;
  hoveredText: string;
}
  
export const recipesCards: CardType[] = [{
  id: "reC01",
  linkTo: "/recipe-page01",
  imageSrc: "/recipe-card-image02.jpg",
  title: "Croutons with omelette",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
}, {
  id: "reC02",
  linkTo: "/recipe-page02",
  imageSrc: "/recipe-card-image10.jpg",
  title: "Chicken broth with vegetables",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
}, {
  id: "reC03",
  linkTo: "/recipe-page03",
  imageSrc: "/recipe-card-image06.jpg",
  title: "Poached eggs on rye buns",
  mealTime: "Brunch",
  hoveredText: "See recipe now!",
},{
  id: "reC04",
  linkTo: "/recipe-page04",
  imageSrc: "/recipe-card-image12.jpg",
  title: "Baked salmon with herbs",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC05",
  linkTo: "/recipe-page05",
  imageSrc: "/recipe-card-image01.jpg",
  title: "Pancakes with honey and blackberries",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
}, {
  id: "reC06",
  linkTo: "/recipe-page06",
  imageSrc: "/recipe-card-image13.jpg",
  title: "Pasta with champignons",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC07",
  linkTo: "/recipe-page07",
  imageSrc: "/recipe-card-image15.jpg",
  title: "Grilled shrimp salad",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC08",
  linkTo: "/recipe-page08",
  imageSrc: "/recipe-card-image18.jpg",
  title: "Meatloaf with prunes and juniper",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
}, {
  id: "reC09",
  linkTo: "/recipe-page09",
  imageSrc: "/recipe-card-image16.jpg",
  title: "Strawberries and arugula salad",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
}, {
  id: "reC10",
  linkTo: "/recipe-page10",
  imageSrc: "/recipe-card-image20.jpg",
  title: "Chocolate custard cream",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC11",
  linkTo: "/recipe-page11",
  imageSrc: "/recipe-card-image08.jpg",
  title: "Guacamole and Tuna Toast",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
}, {
  id: "reC12",
  linkTo: "/recipe-page12",
  imageSrc: "/recipe-card-image03.jpg",
  title: "Egg on toast",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
}, {
  id: "reC13",
  linkTo: "/recipe-page13",
  imageSrc: "/recipe-card-image07.jpg",
  title: "Cheese casserole",
  mealTime: "Brunch",
  hoveredText: "See recipe now!",
}, {
  id: "reC14",
  linkTo: "/recipe-page14",
  imageSrc: "/recipe-card-image19.jpg",
  title: "Chicken legs in honey sauce",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC15",
  linkTo: "/recipe-page15",
  imageSrc: "/recipe-card-image04.jpg",
  title: "Granola and raspberries in yogurt",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
}, {
  id: "reC16",
  linkTo: "/recipe-page16",
  imageSrc: "/recipe-card-image17.jpg",
  title: "Grilled beef steaks",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC17",
  linkTo: "/recipe-page17",
  imageSrc: "/recipe-card-image05.jpg",
  title: "Pancakes with cottage cheese",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
}, {
  id: "reC18",
  linkTo: "/recipe-page18",
  imageSrc: "/recipe-card-image14.jpg",
  title: "Feta and olives salad",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC19",
  linkTo: "/recipe-page19",
  imageSrc: "/recipe-card-image11.jpg",
  title: "Creamy fish soup",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
}, {
  id: "reC20",
  linkTo: "/recipe-page20",
  imageSrc: "/recipe-card-image09.jpg",
  title: "Cheese pie with bacon",
  mealTime: "Brunch 🍽 Lunch",
  hoveredText: "See recipe now!",
}, {
  id: "reC21",
  linkTo: "/recipe-page21",
  imageSrc: "/recipe-card-image21.jpg",
  title: "Lemon cream jelly",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
}, {
  id: "reC22",
  linkTo: "/recipe-page22",
  imageSrc: "/recipe-card-image22.jpg",
  title: "Cod with vegetables",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC23",
  linkTo: "/recipe-page23",
  imageSrc: "/recipe-card-image23.jpg",
  title: "Mint lemonade",
  mealTime: "Brunch 🍽 Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC24",
  linkTo: "/recipe-page24",
  imageSrc: "/recipe-card-image24.jpg",
  title: "Curd cookies",
  mealTime: "Breakfast 🍽 Brunch 🍽 Lunch",
  hoveredText: "See recipe now!",
}, {
  id: "reC25",
  linkTo: "/recipe-page25",
  imageSrc: "/recipe-card-image25.jpg",
  title: "Meatballs in tomato sauce",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC26",
  linkTo: "/recipe-page26",
  imageSrc: "/recipe-card-image26.jpg",
  title: "Baked apples with cinnamon",
  mealTime: "Brunch 🍽 Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC27",
  linkTo: "/recipe-page27",
  imageSrc: "/recipe-card-image27.jpg",
  title: "Eggplant with cheese",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
}, {
  id: "reC28",
  linkTo: "/recipe-page28",
  imageSrc: "/recipe-card-image28.jpg",
  title: "Oatmeal with nuts",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
}];