interface CardType {
  id: string | number | bigint;
  linkTo: string;
  imageSrc: string;
  title: string;
  mealTime: string;
  hoveredText: string;
  ingredients: string[];
  recipeText: string;
}
  
export const recipesCards: CardType[] = [{
  id: "reC01",
  linkTo: "/recipe-page01",
  imageSrc: "/recipe-card-image02.jpg",
  title: "Croutons with omelette",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
  ingredients: 
  [
    "Ingredients", 
    "🍽 3 thick slices rustic rye bread cut from a loaf", 
    "🍽 1 tbsp extra-virgin olive oil",
    "🍽 Salt and pepper",
    "🍽 6 large eggs",
    "🍽 1 tbsp butter, divided",
    "🍽 2,5 tbsp chopped flat-leaf parsley, divided",
    "🍽 1,5 tbsp chopped chives, divided",
    "🍽 0,5 cup shredded Gruyere cheese, divided"
  ],
  recipeText: "Preheat oven to 400°. Cut bread slices into 1/2-in. cubes. In a bowl, toss cubes with oil. Spread on a baking sheet, season with a pinch each of salt and pepper, and bake until crisp, 8 to 10 minutes. In a bowl, whisk eggs with salt and pepper to taste. Heat 1/2 tbsp. butter in an 8-in. nonstick frying pan over medium heat until foam subsides. Pour half of eggs into pan and swirl to spread to edges of pan. Sprinkle with 1 tbsp. parsley and 1/2 tbsp. chives. Lift edge of eggs with a heatproof flexible spatula and tilt pan to let uncooked egg flow underneath. Continue lifting edge and tilting pan, working your way around all sides, until eggs are just set and top is still a little moist, about 2 minutes total. Sprinkle 1/4 cup cheese and 1/2 cup croutons over half of omelet. Loosen omelet with spatula. Tip pan to slide omelet, filled side first, onto a warmed plate; flip bare half over cheese as omelet leaves pan. Make a second omelet the same way. Sprinkle remaining herbs over omelets just before serving.",
}, {
  id: "reC02",
  linkTo: "/recipe-page02",
  imageSrc: "/recipe-card-image10.jpg",
  title: "Chicken broth with vegetables",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  [
    "Ingredients", 
    "🍽 2 tbsp olive oil", 
    "🍽 1 leek, halved, washed, thinly sliced",
    "🍽 2 garlic cloves, crushed",
    "🍽 1 large carrot, peeled, diced",
    "🍽 2 sticks celery, diced",
    "🍽 2 small zucchini, diced",
    "🍽 1 swede or turnip, peeled, diced",
    "🍽 1,25 cups dry soup mix, rinsed",
    "🍽 8 cups chicken style liquid stock",
    "🍽 1kg chicken legs",
  ],
  recipeText: "Heat oil in a large saucepan over medium heat. Add leek and garlic. Cook, stirring, for 2 minutes or until soft but not coloured. Add carrot, celery, zucchini and swede. Cook for 2 minutes. Stir in soup mix, stock, chicken and 1 cup cold water. Increase heat to high. Bring to the boil. Reduce heat to low. Simmer, partially covered, stirring occasionally, for 1 hour or until soup mix and vegetables are tender. Remove chicken legs from soup. Allow to cool slightly. Remove meat from bones. Roughly chop chicken meat and add to soup. Season with salt and pepper. Ladle soup into warmed bowls.",
}, {
  id: "reC03",
  linkTo: "/recipe-page03",
  imageSrc: "/recipe-card-image06.jpg",
  title: "Poached eggs on rye buns",
  mealTime: "Brunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 4 slices of rye sourdough bread, toasted", 
    "🍽 20g butter, softened", 
    "🍽 300g fresh spinach",
    "🍽 4 eggs",
  ],
  recipeText: "Prepare four slices of toast, lightly butter each slice and place on warmed plates. Meanwhile place the spinach in a steamer over a pan of simmering water and steam for three minutes until it has wilted. Squeeze out any excess moisture from the spinach and season with a little salt and pepper. Place a quarter of the spinach on each piece of toast. Fill a wide pan with hot water to the depth of 5cm and bring to a simmer. Break each egg into a cup and then slip the egg into the water leaving plenty of space between each one. Set a timer for two minutes. Keep the water at a gentle simmer – just checking there are small bubbles rising from the bottom of the pan. After two minutes turn the heat off from under the pan and gently baste the eggs with the hot water until they are as cooked as you like them. After two minutes cooking time the white will be cooked and the yolk will be runny. After five minutes the yolk will be soft. Leave a little longer in the pan if you like the eggs well done. Remove the eggs from the pan using a draining spoon or fish slice, dab on a piece of kitchen paper to absorb any excess liquid and serve on top of toast topped with spinach.",
},{
  id: "reC04",
  linkTo: "/recipe-page04",
  imageSrc: "/recipe-card-image12.jpg",
  title: "Baked salmon with herbs",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1 (2 to 2,5-pound) skinless salmon fillet", 
    "🍽 Salt and freshly ground black pepper", 
    "🍽 0,25 cup good olive oil",
    "🍽 2 tbsp freshly squeezed lemon juice",
    "🍽 0,5 cup minced scallions, white and green parts (4 scallions)",
    "🍽 0,5 cup minced fresh dill",
    "🍽 0,5 cup minced fresh parsley",
    "🍽 0,25 cup dry white wine",
    "🍽 Lemon wedges, for serving",
  ],
  recipeText: "Preheat the oven to 425 degrees. Place the salmon fillet in a glass, ceramic, or stainless-steel roasting dish and season it generously with salt and pepper. Whisk together the olive oil and lemon juice and drizzle the mixture evenly over the salmon. Let it stand at room temperature for 15 minutes. In a small bowl, stir together the scallions, dill, and parsley. Scatter the herb mixture over the salmon fillet, turning it so that both sides are generously coated with the green herbs. Pour the wine around the fish fillet. Roast the salmon for 10 to 12 minutes, until almost cooked in the center at the thickest part. The center will be firm with just a line of uncooked salmon in the very center. (I peek by inserting the tip of a small knife.) Cover the dish tightly with aluminum foil and allow to rest for 10 minutes. Cut the salmon crosswise into serving pieces and serve hot with lemon wedges.",
}, {
  id: "reC05",
  linkTo: "/recipe-page05",
  imageSrc: "/recipe-card-image01.jpg",
  title: "Pancakes with honey and blackberries",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
  ingredients:
  ["Ingredients",
    "🍽 300g self-raising flour", 
    "🍽 50g sugar", 
    "🍽 4 eggs",
    "🍽 150ml natural yoghurt",
    "🍽 2 eating apples, peeled and chopped",
    "🍽 Milk Butter to cook the pancakes",
    "🍽 200g blackberries (or blueberries)",
    "🍽 2-3 tbsp Honey",
    "🍽 Juice of 1 lemon",
  ],
  recipeText: "Place all the batter ingredients in the processor. Whizz until well blended. Heat a non–stick pan & add a touch of butter. Add 4 large spoonfuls of batter, spaced well apart and cook for 2 minutes until bubbles appear, flip and cook for another minute. Transfer to a plate and keep warm while you cook the rest (makes about 16). To make the sauce – Heat the fruit, honey and lemon juice until you have a nice thick fruity sauce. Serve warm with the pancakes and extra Yoghurt if you wish.",
}, {
  id: "reC06",
  linkTo: "/recipe-page06",
  imageSrc: "/recipe-card-image13.jpg",
  title: "Pasta with champignons",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 4 tbsp extra-virgin olive oil", 
    "🍽 1 lb. mixed mushrooms torn into bite-size pieces",
    "🍽 Salt", 
    "🍽 2 medium shallots, finely chopped",
    "🍽 1 lb. spaghetti or bucatini",
    "🍽 0,5 cup heavy cream",
    "🍽 0,3 cup finely chopped parsley ",
    "🍽 Zest and juice of 0,5 lemon",
    "🍽 2 tbsp unsalted butter, cut into pieces",
    "🍽 0,5 cup Parmesan, finely grated",
    "🍽 Freshly ground black pepper",
  ],
  recipeText: "Heat 2 tbsp oil in a Dutch oven or other large pot over medium-high. Cook half of mushrooms in a single layer, undisturbed, until edges are brown and starting to crisp, about 3 minutes. Give mushrooms a toss and continue to cook, tossing occasionally, until all sides are brown and crisp, about 5 minutes more. Using a slotted spoon, transfer mushrooms to a plate; season with salt. Repeat with remaining 2 tbsp oil and mushrooms and more salt. Reduce heat to medium-low and return all of the mushrooms to the pot. Add shallots and cook, stirring often, until shallots are translucent and softened, about 2 minutes. Meanwhile, cook pasta in a large pot of boiling salted water, stirring occasionally, until very al dente, about 2 minutes less than package directions. Using tongs, transfer pasta to pot with mushrooms and add cream and 1 cup pasta cooking liquid. Increase heat to medium, bring to a simmer, and cook, tossing constantly, until pasta is al dente and liquid is slightly thickened, about 3 minutes. Remove pot from heat. Add lemon zest and juice, parsley, butter, ½ oz. Parmesan, and lots of pepper and toss to combine. Taste and season with more salt if needed. Divide pasta among bowls and top with more Parmesan.",
}, {
  id: "reC07",
  linkTo: "/recipe-page07",
  imageSrc: "/recipe-card-image15.jpg",
  title: "Grilled shrimp salad",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1 tbsp vegetable oil", 
    "🍽 16-20 jumbo shrimp", 
    "🍽 1 cup citrus Garlic Mojo Sauce",
    "🍽 4 cups arugula",
    "🍽 1 cup julienne jicama",
    "🍽 1 cup diced avocado",
    "🍽 1 cup diced mango",
    "🍽 4 oz lime vinaigrette",
    "🍽 Salt and pepper to taste",
  ],
  recipeText: "Heat grill to medium and lightly oil grates. Assemble shrimp skewers. Use two long skewers, threading 1 skewer through the head end of the shrimp and one through the tail. Season with salt and pepper. Grill until shrimp begins to turn opaque, about 2-3 minutes. Flip and brush liberally with citrus mojo sauce and cook until opaque throughout (about 3-4 minutes), while brushing on more sauce. Place arugula, jicama, avocado and mango in a bowl and toss with lime vinaigrette. Place onto serving plate and top with grilled shrimp.",
}, {
  id: "reC08",
  linkTo: "/recipe-page08",
  imageSrc: "/recipe-card-image18.jpg",
  title: "Meatloaf with prunes",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 0,3 cup whole milk", 
    "🍽 1 cup fine fresh bread crumbs", 
    "🍽 1 medium onion, finely chopped",
    "🍽 3 garlic cloves, minced",
    "🍽 1 medium celery rib, finely chopped",
    "🍽 1 medium carrot, finely chopped",
    "🍽 2 tbsp unsalted butter",
    "🍽 2 tbsp Worcestershire sauce",
    "🍽 1 tbsp cider vinegar",
    "🍽 0,25 tsp ground allspice",
    "🍽 0,25 pound bacon (about 4 slices), chopped",
    "🍽 0,5 cup pitted prunes, chopped",
    "🍽 1,5 pounds ground beef chuck",
    "🍽 0,5 pound ground pork (not lean)",
    "🍽 2 large eggs",
    "🍽 0,3 cup finely chopped flat-leaf parsley",
    "🍽 Garnish: cooked bacon",
  ],
  recipeText: "Preheat oven to 350°F with rack in middle. Soak bread crumbs in milk in a large bowl. Meanwhile, cook onion, garlic, celery, and carrot in butter in a large heavy skillet over medium heat, stirring occasionally, 5 minutes. Cover skillet and reduce heat to low, then cook until carrot is tender, about 5 minutes. Remove from heat and stir in Worcestershire sauce, vinegar, allspice, 2 teaspoons salt, and 1 1/2 teaspoons pepper. Add to bread-crumb mixture. Finely chop bacon and prunes in a food processor, then add to onion mixture along with beef, pork, eggs, and parsley and mix together with your hands. Pack mixture into a 9- by 5-inch oval loaf in a 13- by 9-inch shallow baking dish or pan. Bake until an instant-read thermometer inserted into center of meatloaf registers 155°F, 1 to 1 1/4 hours. Let stand 10 minutes before serving.",
}, {
  id: "reC09",
  linkTo: "/recipe-page09",
  imageSrc: "/recipe-card-image16.jpg",
  title: "Strawberries and arugula salad",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 3 tbsp olive oil", 
    "🍽 2 tbsp balsamic vinegar", 
    "🍽 Salt",
    "🍽 Freshly ground black pepper", 
    "🍽 5 ounces arugula (about 5 packed cups)", 
    "🍽 2 cups sliced strawberries",
    "🍽 0,5 cup roasted pistachios", 
    "🍽 2 tbsp chopped fresh basil leaves", 
  ],
  recipeText: "Whisk the olive oil, balsamic vinegar, a pinch of salt, and a few grinds of black pepper together in a large bowl. Add arugula and strawberries and toss to combine. Add the pistachios and basil and toss again lightly.",
}, {
  id: "reC10",
  linkTo: "/recipe-page10",
  imageSrc: "/recipe-card-image20.jpg",
  title: "Chocolate custard cream",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 60g chocolate bar", 
    "🍽 1 tbsp cake flour(*)", 
    "🍽 1 tbsp corn starch(*)",
    "🍽 1 rounded tablespoon sugar(*)", 
    "🍽 1 egg (whole egg)(*)",
    "🍽 200ml milk(*)", 
    "🍽 1 few drops vanilla oil (or vanilla essence)(*)",
    "🍽 1 grand Marnier or Cointreau (or your favorite liqueur)(*)", 
    "🍽 5g butter",
  ],
  recipeText: "Chop up the chocolate. Put the ingredients(*) in a small sauce pan and mix well before you heat. (If you want to have a smooth silky texture, strain the mixture through a sieve here). Heat over low heat and keep stirring. Once it starts to thicken, it hardens quickly, so keep stirring! Once it becomes shiny and hardens a little, add the chopped chocolate and mix well. Turn off the heat, add the butter and mix. The chocolate blends in very quickly. When you cool the custard cream, cover with cling film. Make sure it touches the surface of the custard cream. This will prevent the surface from drying out. If you chill the custard cream in the fridge, it will set firmly. Use it as a bread filling and so on. There are so many ways you can use it. A small sauce pan and whisk are better when making this custard cream. Use 1 leveled tablespoon of cake flour and corn starch. Use 1 rounded tablespoon of granulated sugar. FYI: We don't strain the mixture through a sieve in Step 2, but it's still delicious (It may have some tiny lumpy bits).",
}, {
  id: "reC11",
  linkTo: "/recipe-page11",
  imageSrc: "/recipe-card-image08.jpg",
  title: "Guacamole and Tuna Toast",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 185g can Safcol Tuna in Springwater", 
    "🍽 2 slices sourdough bread", 
    "🍽 1 purple onion sliced",
    "🍽 1 avocado sliced or mashed", 
    "🍽 Salt and freshly ground black pepper", 
  ],
  recipeText: "While lightly toast two slices of sourdough, roughly mash the avocado, and finely slice a few rings of purple onion. When the toast is ready, liberally add the avocado, purple onion, and few chunks of tuna. Season to taste.",
}, {
  id: "reC12",
  linkTo: "/recipe-page12",
  imageSrc: "/recipe-card-image03.jpg",
  title: "Egg on toast",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1 slice bread", 
    "🍽 2 tbsp butter, melted", 
    "🍽 1 large egg",
    "🍽 Salt to taste",
  ],
  recipeText: "Cut a circle in the center of bread with a cookie cutter. Brush melted butter on both sides of bread. Heat a small skillet over medium heat. Add bread and cook until golden brown, about 2 minutes. Flip, then crack egg into the hole. Cook until egg is set on the bottom, about 1 minute; season with salt. Cover, reduce the heat to low, and cook until egg white is completely set, 3 to 4 minutes.",
}, {
  id: "reC13",
  linkTo: "/recipe-page13",
  imageSrc: "/recipe-card-image07.jpg",
  title: "Cheese casserole",
  mealTime: "Brunch",
  hoveredText: "See recipe now!",
  ingredients: ["Ingredients",
    "🍽 1 lb. hot ground pork sausage", 
    "🍽 1,25 cups shredded Parmesan cheese", 
    "🍽 1 tsp. salt",
    "🍽 6 green onions, sliced", 
    "🍽 1 package mini croissants (about 24), torn", 
    "🍽 Vegetable cooking spray",
    "🍽 3 cups milk", 
    "🍽 1 cup heavy cream", 
    "🍽 5 large eggs, lightly beaten",
    "🍽 2 cups shredded Gruyère cheese",
  ],
  recipeText: "Cook sausage about 8 minutes in a skillet over medium-high heat, stirring to crumble. Toss together sausage, Parmesan cheese, and next 3 ingredients; arrange mixture in a 13- x 9-inch baking dish coated with cooking spray. Whisk together milk and next 2 ingredients; pour over the sausage mixture. Cover and chill dish for 8 hours. Preheat oven to 350°F. Uncover casserole, and sprinkle with Gruyère cheese. Bake 45 minutes or until golden. Let stand 10 minutes.",
}, {
  id: "reC14",
  linkTo: "/recipe-page14",
  imageSrc: "/recipe-card-image19.jpg",
  title: "Chicken legs in honey sauce",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1.5kg chicken drumsticks", 
    "🍽 0,5 tbsp baking powder", 
    "🍽 0,5 tbsp sea salt",
    "🍽 Vegetable oil for brushing", 
    "🍽 Sesame seeds, to serve (optional)", 
    "🍽 1 tbsp vegetable oil",
    "🍽 2 garlic cloves, finely chopped", 
    "🍽 1 cup chicken stock", 
    "🍽 2 tbsp white vinegar",
    "🍽 3 tbsp honey", 
    "🍽 1 tbsp soy sauce", 
    "🍽 4 tbsp sugar",
    "🍽 1 tsp corn flour (cornstarch) mixed with 1 tbsp water", 
  ],
  recipeText: "Preheat the oven to 120°C/250°F. Use paper towel to pat the drumsticks dry. Transfer the drumsticks to a large bowl and add the baking powder and salt. Mix well, ensuring the baking powder is evenly distributed. Place a rack onto a baking tray and brush the rack with oil. Lay the drumsticks out on the rack. Bake in the oven for 30 minutes. Increase oven heat to 200°C/390°F and cook for another 45 minutes or until crispy and cooked through. In the meantime, make the sauce. Heat the vegetable oil in a small saucepan over medium heat. Add the garlic and cook for half a minute. Then add the chicken stock, vinegar, honey, soy sauce and sugar. Cook, stirring every so often, for 10 minutes or until the sugar has dissolved and the sauce has thickened slightly. Stir through the corn flour mixture and simmer for another half a minute or until thickened. Set aside to cool. To serve, drizzle with honey sauce over the chicken drumsticks and toss until well coated. Sprinkle with sesame seeds and serve.",
}, {
  id: "reC15",
  linkTo: "/recipe-page15",
  imageSrc: "/recipe-card-image04.jpg",
  title: "Granola and raspberries in yogurt",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1 plain yogurt cup", 
    "🍽 0,3 cup granola", 
    "🍽 1 tsp cinnamon",
    "🍽 0,25 cup raspberries", 
    "🍽 1 tsp honey", 
  ],
  recipeText: "Add yogurt, granola, cinnamon and raspberries to a bowl. Drizzle with honey and enjoy!",
}, {
  id: "reC16",
  linkTo: "/recipe-page16",
  imageSrc: "/recipe-card-image17.jpg",
  title: "Grilled beef steaks",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1 small onion, chopped", 
    "🍽 7 cloves garlic", 
    "🍽 0,5 cup olive oil",
    "🍽 0,5 cup vinegar", 
    "🍽 0,5 cup soy sauce", 
    "🍽 2 tbsp chopped fresh rosemary",
    "🍽 2 tbsp Dijon-style prepared mustard", 
    "🍽 2 tsp salt", 
    "🍽 1 tsp black pepper",
    "🍽 1 (2 pound) tri-tip steak", 
    "🍽 1 tbsp vegetable oil for greasing", 
  ],
  recipeText: "Place onion, garlic, olive oil, vinegar, soy sauce, rosemary, mustard, salt, and pepper into the bowl of a food processor. Process until marinade is smooth.Place steak in a large resealable plastic bag. Pour marinade over steak; seal the bag and refrigerate for about 3 hours. Preheat the grill for high heat. Brush the grate with oil. Remove steak from marinade and place on the prepared grill grate; discard marinade. Cook on the preheated grill to desired doneness or about 7 minutes per side.",
}, {
  id: "reC17",
  linkTo: "/recipe-page17",
  imageSrc: "/recipe-card-image05.jpg",
  title: "Pancakes with cottage cheese",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 0,5 cup old-fashioned oats", 
    "🍽 0,5 cup cottage cheese", 
    "🍽 2 large eggs",
    "🍽 0,1 tsp salt", 
    "🍽 Maple syrup, jam, or sliced berries, for serving", 
  ],
  recipeText: "Place 0,5 cup old-fashioned oats, 0,5 cup cottage cheese, 2 large eggs, and 0,1 teaspoon salt in a blender and process on high speed until well-combined, about 30 seconds. Heat a large nonstick frying pan over medium heat. Working in batches, add the batter in 2-tablespoon portions, spacing them evenly apart. Cook until the pancakes are set around the edges and deep golden-brown on the bottom, 2 to 3 minutes (this batter won't bubble up like traditional pancake batter). Gently flip the pancakes with a thin spatula and cook until the second side is golden-brown, 1 to 2 minutes more. Transfer to a plate. Repeat cooking the remaining batter. These pancakes are best when eaten fresh off the griddle and still warm. Serve with maple syrup, honey, or jam.",
}, {
  id: "reC18",
  linkTo: "/recipe-page18",
  imageSrc: "/recipe-card-image14.jpg",
  title: "Feta and olives salad",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1 medium red onion", 
    "🍽 4 medium juicy tomatoes", 
    "🍽 1 cucumber",
    "🍽 1 green bell pepper", 
    "🍽 1 handful pitted Kalamata olives", 
    "🍽 1,5 tsp dried oregano",
    "🍽 Salt", 
    "🍽 0,25 cup extra virgin olive oil", 
    "🍽 1-2 tbsp red wine vinegar",
    "🍽 1 block Greek feta cheese in brine",
  ],
  recipeText: "Shock the onion (optional). If you'd like to mellow the onion's raw taste, fill a small bowl with ice water. Add about 1 teaspoon of red wine vinegar to the water, then add the sliced onion. Set aside to soak for 10 minutes or so. Combine the veggies. Place the tomato, cucumber, bell pepper, and olives in a large serving dish. Remove the onions from the water and add to the dish with the rest of the vegetables. Season. Sprinkle the vegetables with 3/4 teaspoon of oregano and a pinch of kosher salt. Add the oil and vinegar (to your liking) then give everything a gentle toss. Finish and serve. Top the salad with slabs of feta and sprinkle with the remaining 3/4 teaspoon of oregano.",
}, {
  id: "reC19",
  linkTo: "/recipe-page19",
  imageSrc: "/recipe-card-image11.jpg",
  title: "Creamy fish soup",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 280g salmon, diced", 
    "🍽 280g cod, diced", 
    "🍽 2 tbsp butter",
    "🍽 1 tbsp flour", 
    "🍽 3 dl fish stock", 
    "🍽 3 dl full-fat milk",
    "🍽 3 dl creme fraiche", 
    "🍽 0.5 tsp salt", 
    "🍽 8 turns of a pepper grinder",
    "🍽 1 carrot, sliced thinly", 
    "🍽 1 spring onion, sliced lenghtwise thinly", 
    "🍽 0.25 celeriac, sliced thinly",
    "🍽 1 handfull dill, chopped", 
  ],
  recipeText: "Dice the cod and salmon. Melt the butter and add the flour. Whisk together while slowly adding the fish stock. Once thick and smooth, slowly add the full-fat milk and crème fraîche, then season with salt and pepper. Thinly slice the carrot, spring onion and celeriac and chop the fresh dill. We recommend using a mandolin or carrot peeler to get thin slices of the celeriac. Add the vegetables, dill, salmon and cod to the soup and leave to simmer for 5-6 minutes. Serve piping hot, preferably with freshly baked bread and butter.",
}, {
  id: "reC20",
  linkTo: "/recipe-page20",
  imageSrc: "/recipe-card-image09.jpg",
  title: "Cheese pie with bacon",
  mealTime: "Brunch 🍽 Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1 pie crust, unbaked", 
    "🍽 1 pound sliced bacon, cooked and crumbled", 
    "🍽 1 large tomato, peeled and sliced",
    "🍽 1 cup shredded cheddar cheese", 
    "🍽 3 large eggs, separated", 
    "🍽 0,75 cup sour cream",
    "🍽 0,5 cup all-purpose flour", 
    "🍽 0,5 tsp salt", 
    "🍽 Paprika",
  ],
  recipeText: "Line unpricked pie crust with a double thickness of heavy-duty foil. Bake at 450° for 5 minutes. Remove foil. Bake 5 minutes longer. Cool completely. Sprinkle bacon over the crust. Top with tomato and cheese. In a large bowl, beat the egg yolks, sour cream, flour and salt until smooth. In another large bowl, beat egg whites until stiff. Fold into sour cream mixture; spread over cheese. Sprinkle with paprika. Bake at 350° until a knife inserted in the center comes out clean, about 45 minutes. Let stand 5-10 minutes before cutting.",
}, {
  id: "reC21",
  linkTo: "/recipe-page21",
  imageSrc: "/recipe-card-image21.jpg",
  title: "Lemon cream jelly",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1 lemon", 
    "🍽 4 eggs", 
    "🍽 2 cups sugar",
    "🍽 4 sheets gelatin", 
  ],
  recipeText: "Separate the egg yolks from the whites. Beat the yolks with the sugar. Gradually add half the lemon juice, lemon peel and gelatin (pre-soaked in cold water and dissolved in 2 tablespoons hot water). Finally, add the beaten egg whites. tir the mixture well and pour it into a form that you've rinsed with cold water. Leave to cool.",
}, {
  id: "reC22",
  linkTo: "/recipe-page22",
  imageSrc: "/recipe-card-image22.jpg",
  title: "Cod with vegetables",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 700g of cod, boned and skinned", 
    "🍽 2 tbsp of olive oil", 
    "🍽 1 large red onion",
    "🍽 4 tomatoes, cut into quarters", 
    "🍽 1 red pepper", 
    "🍽 1 yellow pepper",
    "🍽 2 courgettes", 
    "🍽 1 tbsp of rosemary leaves", 
    "🍽 1 tbsp of thyme leaves",
    "🍽 2 tbsp of red pesto", 
    "🍽 Sea salt, to taste", 
    "🍽 Black pepper, to taste",
  ],
  recipeText: "While you are preparing the vegetables, place the cod fillets in a large bowl and add 1 tablespoon olive oil, the herbs, salt and pepper. Mix well and allow to marinade in the herbal oil. Add the remaining oil to a large frying pan and fry the vegetables until they are just cooked and still have a bite to them, about 8 to 10 minutes. Push the cooked vegetables to one side of the pan (or place them in a bowl, cover and keep warm in the oven) and add the cod to the pan. Fry the cod for 2 to 3 minutes on each side until the fish is cooked and it just starts to flake - do not overcook as it will become too dry. Serve the cod immediately on warmed plates with the vegetables and a drizzle of red pesto over the top of each piece of cod. To oven bake, place the vegetables in a large tray and bake at 200C/gas mark 6 for 15 to 20 minutes. Remove the vegetables from the oven and sit the cod steaks on top of the vegetables, cover with foil and cook for a further 10 to 15 minutes until the cod is cooked. Serve as before.",
}, {
  id: "reC23",
  linkTo: "/recipe-page23",
  imageSrc: "/recipe-card-image23.jpg",
  title: "Mint lemonade",
  mealTime: "Brunch 🍽 Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 0,25 cup sugar for simple syrup", 
    "🍽 Ice cubes", 
    "🍽 1,5 cups freshly squeezed lemon juice",
    "🍽 2 tbsp julienned mint, plus leaves for garnish", 
    "🍽 1 lemon, sliced 0,25-inch thick", 
  ],
  recipeText: "In a small saucepan, combine sugar and 1/4 cup water. Bring mixture to a boil, stirring until the sugar has dissolved. Remove from heat. Let stand until completely cool. In a large pitcher half-filled with ice, add 2 cups water, lemon juice, simple syrup, mint, and lemon slices. Stir to combine. Serve over ice. Garnish with mint leaves and lemon slices.",
}, {
  id: "reC24",
  linkTo: "/recipe-page24",
  imageSrc: "/recipe-card-image24.jpg",
  title: "Curd cookies",
  mealTime: "Breakfast 🍽 Brunch 🍽 Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1 cup butter unsalted", 
    "🍽 0,5 cup granulated white sugar", 
    "🍽 1 tsp vanilla",
    "🍽 2 cups all purpose flour", 
    "🍽 2 egg yolks", 
    "🍽 Pinch salt",
    "🍽 1 cup lemon curd", 
  ],
  recipeText: "Combine the flour and the salt and set aside. Add the butter and sugar to a large mixing bowl and mix on high until light and fluffy. This will take about 3-4 minutes. Add in the egg yolks and vanilla extract and mix on high for a minute. Add the flour and stir in until combined. Form the dough into a ball, wrap in plastic wrap and chill for about one hour. Line a baking tray with parchment paper and make about 36 balls with your dough. Place them evenly spaced out on your baking tray (in batches) and use your thumb to make an impression in the middle of each ball. Bake in a preheated 350 degree F/180 degrees C oven for about 12 minutes. Remove from oven and place on a cooling rack. Fill the centres with lemon curd while the cookies are still warm. Allow the cookies to cool and set at room temperature. Store in an airtight container between sheets of parchment paper. Keep in the fridge up to about four days.",
}, {
  id: "reC25",
  linkTo: "/recipe-page25",
  imageSrc: "/recipe-card-image25.jpg",
  title: "Meatballs in tomato sauce",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 500g lean beef mince", 
    "🍽 10ml Ina Paarman's Garlic Pepper Seasoning", 
    "🍽 125ml soft breadcrumbs (white or brown)",
    "🍽 60ml Ina Paarman's Roast Onion Soup and Gravy Powder", 
    "🍽 250ml cold water", 
    "🍽 30ml olive oil",
    "🍽 400g tomato & basil Pasta Sauce", 
    "🍽 Chives to garnish",
  ],
  recipeText: "Mix all the ingredients for the meatballs, except the oil, lightly together with a small knife. Leave to rest for 10 minutes. Divide the mixture and roll into ten balls. Brown them lightly all round in the oil in a biggish saucepan or frying pan. Add the Tomato & Basil Pasta Sauce to the browned meatballs, pour the water into the pasta bottle, shake to remove every last drop of sauce, and add to pan. Turn the heat down to low, place a lid on the saucepan and simmer slowly for 20 minutes. Serve with spaghetti, rice or mashed potatoes and the vegetables or salad of your choice. Garnish with snipped chives.",
}, {
  id: "reC26",
  linkTo: "/recipe-page26",
  imageSrc: "/recipe-card-image26.jpg",
  title: "Baked apples with cinnamon",
  mealTime: "Brunch 🍽 Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 6-7 medium to large apples", 
    "🍽 2 tbsp lemon juice", 
    "🍽 1 tbsp coconut oil",
    "🍽 0,5 cup coconut sugar", 
    "🍽 1,5 tsp ground cinnamon", 
    "🍽 0,5 tsp fresh grated ginger*",
    "🍽 1 pinch nutmeg", 
    "🍽 3 tbsp cornstarch or arrowroot starch", 
    "🍽 3 tbsp fresh apple juice or water",
    "🍽 1 pinch sea salt",
  ],
  recipeText: "Preheat oven to 350 degrees F (176 C) and set out a 9x13-inch (or similar size) baking dish. Peel and core apples, quarter, and use a paring knife to thinly slice lengthwise. The thinner the better! Just try to be consistent so they cook evenly.Add to baking dish and top with lemon juice, coconut oil (optional), coconut sugar, cinnamon, ginger, nutmeg, cornstarch (or arrowroot), apple juice (or water), and a healthy pinch of salt. Toss to combine. Then loosely cover with foil. Bake for 45 minutes (covered). Then carefully remove foil and bake for an additional 10-15 minutes or until the apples are very fork tender (especially in the center of the dish) and slightly caramelized. Enjoy as is or with Coconut Whipped Cream or Vanilla Bean Coconut Ice Cream! Best when fresh, though leftovers keep covered in the refrigerator up to 3-4 days or in the freezer up to 1 month. Reheat in the microwave or in a 350-degree F (176 C) oven (covered) until warmed through. Add a bit of water if the “caramel” sauce is too thick.",
}, {
  id: "reC27",
  linkTo: "/recipe-page27",
  imageSrc: "/recipe-card-image27.jpg",
  title: "Eggplant with cheese",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 2 large eggplant", 
    "🍽 Olive oil", 
    "🍽 Salt, to taste",
    "🍽 Freshly ground black pepper, to taste", 
    "🍽 0,5 small brown onion, diced", 
    "🍽 2 cloves garlic, minced",
    "🍽 1 medium tomato, diced", 
    "🍽 1 tbsp tomato paste", 
    "🍽 Pinch cayenne pepper",
    "🍽 100g mushrooms, diced", 
    "🍽 80g mozzarella, grated",
    "🍽 2 tbsp flat leaf parsley, roughly chopped, to serve", 
  ],
  recipeText: "Preheat oven to 200C. Cut each eggplant in half, leaving the tops intact. Use a sharp knife to score the flesh, then place on a baking tray with the cut side facing up. Drizzle with olive oil and season to taste. Bake for 30 minutes or until the eggplant are soft. Meanwhile, add a splash of olive oil to a frying pan over medium heat. Add onion and garlic, and cook for 3 minutes, or until the onion starts to soften. Add tomato, tomato paste, and cayenne pepper, and cook until the tomato softens. Remove the flesh from the roasted eggplants and roughly chop. Reserve eggplant skins. Add eggplant flesh and mushrooms to the pan and continue cooking until the mushrooms are softened. Season to taste, then remove from the heat. Spoon mixture in eggplant skins and sprinkle over grated mozzarella. Cook, in oven, until the cheese is melted and golden, about 7 minutes. Serve immediately.",
}, {
  id: "reC28",
  linkTo: "/recipe-page28",
  imageSrc: "/recipe-card-image28.jpg",
  title: "Oatmeal with nuts",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 0,5 cup old-fashioned oats", 
    "🍽 1 cup skim milk", 
    "🍽 0,25 cup nonfat plain Greek yogurt",
    "🍽 0,25 cup chopped apple", 
    "🍽 1 tbsp walnuts, toasted if desired",
  ],
  recipeText: "Combine oats and milk in a small saucepan. Bring just to a boil over high heat; then reduce the heat to medium and cook, stirring frequently, until the oats are tender and creamy, 4 to 5 minutes. Remove from the heat, cover and let stand for 2 minutes. Serve topped with yogurt, apple and walnuts.",
}];