interface CardType {
  id: string | number | bigint;
  linkTo: string;
  imageSrc: string;
  title: string;
  mealTime: string;
  hoveredText: string;
  ingredients: string[];
  recipeText: string;
}
  
export const recipesCards: CardType[] = [{
  id: "reC01",
  linkTo: "/recipe-page01",
  imageSrc: "/recipe-card-image02.jpg",
  title: "Croutons with omelette",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
  ingredients: 
  [
    "Ingredients", 
    "🍽 3 thick slices rustic rye bread cut from a loaf, crusts trimmed", 
    "🍽 1 tablespoon extra-virgin olive oil",
    "🍽 Salt and pepper",
    "🍽 6 large eggs",
    "🍽 1 tablespoon butter, divided",
    "🍽 2,5 tablespoons chopped flat-leaf parsley, divided",
    "🍽 1,5 tablespoons chopped chives, divided",
    "🍽 0,5 cup shredded Gruyère cheese, divided"
  ],
  recipeText: "Preheat oven to 400°. Cut bread slices into 1/2-in. cubes. In a bowl, toss cubes with oil. Spread on a baking sheet, season with a pinch each of salt and pepper, and bake until crisp, 8 to 10 minutes. In a bowl, whisk eggs with salt and pepper to taste. Heat 1/2 tbsp. butter in an 8-in. nonstick frying pan over medium heat until foam subsides. Pour half of eggs into pan and swirl to spread to edges of pan. Sprinkle with 1 tbsp. parsley and 1/2 tbsp. chives. Lift edge of eggs with a heatproof flexible spatula and tilt pan to let uncooked egg flow underneath. Continue lifting edge and tilting pan, working your way around all sides, until eggs are just set and top is still a little moist, about 2 minutes total. Sprinkle 1/4 cup cheese and 1/2 cup croutons over half of omelet. Loosen omelet with spatula. Tip pan to slide omelet, filled side first, onto a warmed plate; flip bare half over cheese as omelet leaves pan. Make a second omelet the same way. Sprinkle remaining herbs over omelets just before serving.",
}, {
  id: "reC02",
  linkTo: "/recipe-page02",
  imageSrc: "/recipe-card-image10.jpg",
  title: "Chicken broth with vegetables",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  [
    "Ingredients", 
    "🍽 2 tbsp olive oil", 
    "🍽 1 leek, halved, washed, thinly sliced",
    "🍽 2 garlic cloves, crushed",
    "🍽 1 large carrot, peeled, diced",
    "🍽2 sticks celery, diced",
    "🍽 2 small zucchini, diced",
    "🍽 1 swede or turnip, peeled, diced",
    "🍽 1,25 cups dry soup mix, rinsed",
    "🍽 8 cups chicken style liquid stock",
    "🍽 1kg chicken legs",
  ],
  recipeText: "Heat oil in a large saucepan over medium heat. Add leek and garlic. Cook, stirring, for 2 minutes or until soft but not coloured. Add carrot, celery, zucchini and swede. Cook for 2 minutes. Stir in soup mix, stock, chicken and 1 cup cold water. Increase heat to high. Bring to the boil. Reduce heat to low. Simmer, partially covered, stirring occasionally, for 1 hour or until soup mix and vegetables are tender. Remove chicken legs from soup. Allow to cool slightly. Remove meat from bones. Roughly chop chicken meat and add to soup. Season with salt and pepper. Ladle soup into warmed bowls. Serve.",
}, {
  id: "reC03",
  linkTo: "/recipe-page03",
  imageSrc: "/recipe-card-image06.jpg",
  title: "Poached eggs on rye buns",
  mealTime: "Brunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 4 slices of rye sourdough bread, toasted", 
    "🍽 20g butter, softened", 
    "🍽 300g fresh spinach",
    "🍽  4 eggs",
  ],
  recipeText: "Prepare four slices of toast, lightly butter each slice and place on warmed plates. Meanwhile place the spinach in a steamer over a pan of simmering water and steam for three minutes until it has wilted. Squeeze out any excess moisture from the spinach and season with a little salt and pepper. Place a quarter of the spinach on each piece of toast. Fill a wide pan with hot water to the depth of 5cm and bring to a simmer. Break each egg into a cup and then slip the egg into the water leaving plenty of space between each one. Set a timer for two minutes. Keep the water at a gentle simmer – just checking there are small bubbles rising from the bottom of the pan. After two minutes turn the heat off from under the pan and gently baste the eggs with the hot water until they are as cooked as you like them. After two minutes cooking time the white will be cooked and the yolk will be runny. After five minutes the yolk will be soft. Leave a little longer in the pan if you like the eggs well done. Remove the eggs from the pan using a draining spoon or fish slice, dab on a piece of kitchen paper to absorb any excess liquid and serve on top of toast topped with spinach.",
},{
  id: "reC04",
  linkTo: "/recipe-page04",
  imageSrc: "/recipe-card-image12.jpg",
  title: "Baked salmon with herbs",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 1 (2 to 2,5-pound) skinless salmon fillet", 
    "🍽 Salt and freshly ground black pepper", 
    "🍽 0,25 cup good olive oil",
    "🍽 2 tablespoons freshly squeezed lemon juice",
    "🍽 0,5 cup minced scallions, white and green parts (4 scallions)",
    "🍽 0,5 cup minced fresh dill",
    "🍽 0,5 cup minced fresh parsley",
    "🍽 0,25 cup dry white wine",
    "🍽 Lemon wedges, for serving",
  ],
  recipeText: "Preheat the oven to 425 degrees. Place the salmon fillet in a glass, ceramic, or stainless-steel roasting dish and season it generously with salt and pepper. Whisk together the olive oil and lemon juice and drizzle the mixture evenly over the salmon. Let it stand at room temperature for 15 minutes. In a small bowl, stir together the scallions, dill, and parsley. Scatter the herb mixture over the salmon fillet, turning it so that both sides are generously coated with the green herbs. Pour the wine around the fish fillet. Roast the salmon for 10 to 12 minutes, until almost cooked in the center at the thickest part. The center will be firm with just a line of uncooked salmon in the very center. (I peek by inserting the tip of a small knife.) Cover the dish tightly with aluminum foil and allow to rest for 10 minutes. Cut the salmon crosswise into serving pieces and serve hot with lemon wedges.",
}, {
  id: "reC05",
  linkTo: "/recipe-page05",
  imageSrc: "/recipe-card-image01.jpg",
  title: "Pancakes with honey and blackberries",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
  ingredients:
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC06",
  linkTo: "/recipe-page06",
  imageSrc: "/recipe-card-image13.jpg",
  title: "Pasta with champignons",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC07",
  linkTo: "/recipe-page07",
  imageSrc: "/recipe-card-image15.jpg",
  title: "Grilled shrimp salad",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC08",
  linkTo: "/recipe-page08",
  imageSrc: "/recipe-card-image18.jpg",
  title: "Meatloaf with prunes and juniper",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC09",
  linkTo: "/recipe-page09",
  imageSrc: "/recipe-card-image16.jpg",
  title: "Strawberries and arugula salad",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC10",
  linkTo: "/recipe-page10",
  imageSrc: "/recipe-card-image20.jpg",
  title: "Chocolate custard cream",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {

  id: "reC11",
  linkTo: "/recipe-page11",
  imageSrc: "/recipe-card-image08.jpg",
  title: "Guacamole and Tuna Toast",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC12",
  linkTo: "/recipe-page12",
  imageSrc: "/recipe-card-image03.jpg",
  title: "Egg on toast",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC13",
  linkTo: "/recipe-page13",
  imageSrc: "/recipe-card-image07.jpg",
  title: "Cheese casserole",
  mealTime: "Brunch",
  hoveredText: "See recipe now!",
  ingredients: ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC14",
  linkTo: "/recipe-page14",
  imageSrc: "/recipe-card-image19.jpg",
  title: "Chicken legs in honey sauce",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC15",
  linkTo: "/recipe-page15",
  imageSrc: "/recipe-card-image04.jpg",
  title: "Granola and raspberries in yogurt",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC16",
  linkTo: "/recipe-page16",
  imageSrc: "/recipe-card-image17.jpg",
  title: "Grilled beef steaks",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC17",
  linkTo: "/recipe-page17",
  imageSrc: "/recipe-card-image05.jpg",
  title: "Pancakes with cottage cheese",
  mealTime: "Breakfast",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC18",
  linkTo: "/recipe-page18",
  imageSrc: "/recipe-card-image14.jpg",
  title: "Feta and olives salad",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC19",
  linkTo: "/recipe-page19",
  imageSrc: "/recipe-card-image11.jpg",
  title: "Creamy fish soup",
  mealTime: "Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC20",
  linkTo: "/recipe-page20",
  imageSrc: "/recipe-card-image09.jpg",
  title: "Cheese pie with bacon",
  mealTime: "Brunch 🍽 Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC21",
  linkTo: "/recipe-page21",
  imageSrc: "/recipe-card-image21.jpg",
  title: "Lemon cream jelly",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC22",
  linkTo: "/recipe-page22",
  imageSrc: "/recipe-card-image22.jpg",
  title: "Cod with vegetables",
  mealTime: "Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC23",
  linkTo: "/recipe-page23",
  imageSrc: "/recipe-card-image23.jpg",
  title: "Mint lemonade",
  mealTime: "Brunch 🍽 Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC24",
  linkTo: "/recipe-page24",
  imageSrc: "/recipe-card-image24.jpg",
  title: "Curd cookies",
  mealTime: "Breakfast 🍽 Brunch 🍽 Lunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC25",
  linkTo: "/recipe-page25",
  imageSrc: "/recipe-card-image25.jpg",
  title: "Meatballs in tomato sauce",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC26",
  linkTo: "/recipe-page26",
  imageSrc: "/recipe-card-image26.jpg",
  title: "Baked apples with cinnamon",
  mealTime: "Brunch 🍽 Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC27",
  linkTo: "/recipe-page27",
  imageSrc: "/recipe-card-image27.jpg",
  title: "Eggplant with cheese",
  mealTime: "Lunch 🍽 Dinner",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}, {
  id: "reC28",
  linkTo: "/recipe-page28",
  imageSrc: "/recipe-card-image28.jpg",
  title: "Oatmeal with nuts",
  mealTime: "Breakfast 🍽 Brunch",
  hoveredText: "See recipe now!",
  ingredients: 
  ["Ingredients",
    "🍽 ", 
    "🍽 ", 
    "🍽 ",
  ],
  recipeText: "",
}];